sudo: required
dist: trusty

before_install:
  - sudo apt-get update
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $POSTGRESQL_VERSION
before_script:
  - psql -c 'create database postgresql_audit_test;' -U postgres

language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
env:
  global:
    - TOXENV='py-sqla{0.9,1.0,1.1}'
  matrix:
    - POSTGRESQL_VERSION=9.4
    - POSTGRESQL_VERSION=9.5
    - POSTGRESQL_VERSION=9.6

matrix:
  include:
  - python: 3.6
    env: TOXENV='lint'

install:
  - pip install tox

script:
  - tox
